apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blue
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
      - name: my-web-app
        image: 8if8troin6i4rv2p/capstone-v5
        imagePullPolicy: Always
        ports:
        - containerPort: 80
            
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

kind: Service
metadata:
  name: my-web-service
spec:
  type: ClusterIP
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80