apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
      role: blue
  template:
    metadata:
      labels:
        app: capstone
        role: blue
    spec:
      containers:
        - name: nginx
          image: nginx:blue
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9080
          readinessProbe:
            httpGet:
              path: /
              port: 9080
        - name: myWebApp
          image: 8if8troin6i4rv2p/capstone-v5
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
