apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-blue
  namespace: my-namespace
  labels:
    app: my-web-app
  
  limits:
    - max:
        cpu: "800m"
      min:
        cpu: "200m"
      type: Container  

    spec:
      replicas: 2
      selector:
        matchLabels:
          app: my-app
      template:
        metadata:
          labels:
            app: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64

      containers:
        - name: nginx
          image: nginx:1.19.2
          resources:
            limits:
              cpu: "800m"
            requests:
              cpu: "100m"
        ports:
        - containerPort: 8090

        - name: my-web-app
          image: 8if8troin6i4rv2p/capstone-v5
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          